CREATE TABLE ALUNO (
	IDALUNO SERIAL NOT NULL,
	NOME VARCHAR (70) NOT NULL,
	DATA_NASC DATE NOT NULL,
	SEXO CHAR (1) NOT NULL CHECK ( UPPER(SEXO) = 'M' OR UPPER(SEXO) = 'F'),
	CPF NUMERIC (11) UNIQUE,
	CELULAR NUMERIC (15),
	TELEFONE NUMERIC (15),
	EMAIL VARCHAR (70),
	TP_SANG VARCHAR (2),
	FATOR_RH CHAR (1),

	CONSTRAINT PK_IDALUNO PRIMARY KEY (IDALUNO)
);


CREATE TABLE PERSONAL (
	IDPERSONAL SERIAL NOT NULL,
	NOME VARCHAR (70) NOT NULL,
	DATA_NASC DATE NOT NULL,
	SEXO CHAR (1) NOT NULL CHECK ( UPPER(SEXO) = 'M' OR UPPER(SEXO) = 'F'),
	CPF NUMERIC (11) UNIQUE,
    CREF NUMERIC (15) UNIQUE,
	CELULAR NUMERIC (15),
	TELEFONE NUMERIC (15),
	EMAIL VARCHAR (70),
	
	CONSTRAINT PK_IDPERSONAL PRIMARY KEY (IDPERSONAL)

);

CREATE TABLE ENDERECO (
	IDENDERECO SERIAL NOT NULL,
	RUA VARCHAR (100),
	NUMERO NUMERIC (10),
	BAIRRO VARCHAR (100),
	CIDADE VARCHAR (100),
	ID_ALUNO INT,
    ID_PERSONAL INT,

	CONSTRAINT PK_IDENDERECO PRIMARY KEY (IDENDERECO),
	CONSTRAINT FK_END_ALUNO FOREIGN KEY (ID_ALUNO) REFERENCES ALUNO (IDALUNO),
    CONSTRAINT FK_END_PERSON FOREIGN KEY(ID_PERSONAL) REFERENCES PERSONAL (IDPERSONAL)		
);

CREATE TABLE PLANO (
	IDPLANO SERIAL NOT NULL,
	TIPO_PLANO VARCHAR (50) NOT NULL,
	DATA_INICIO DATE NOT NULL,
	DATA_FINAL DATE,
	DATA_PAG_INIT DATE,
	VALOR_PLANO VARCHAR (10),
	ID_ALUNO INT,	

	CONSTRAINT PK_IDPLANO PRIMARY KEY (IDPLANO),
	CONSTRAINT FK_PLANO_ALUNO FOREIGN KEY (ID_ALUNO) REFERENCES ALUNO (IDALUNO)		
);

CREATE TABLE PAGAMENTO (
	IDPAGAMENTO SERIAL NOT NULL,
	DATA_PGTO DATE,
	DATA_VCTO DATE,
	FORMA_PGTO VARCHAR (15),
    ID_PLANO INT,
	
	CONSTRAINT PK_IDPAGAMENTO PRIMARY KEY (IDPAGAMENTO),
    CONSTRAINT FK_PAG_PLANO FOREIGN KEY (ID_PLANO) REFERENCES PLANO(IDPLANO)			
);

CREATE TABLE AVALIACAO (
	IDAVALIACAO SERIAL NOT NULL,
	DATA_AVAL DATE  NOT NULL,
	PESO NUMERIC (6),
	ALTURA NUMERIC (3),
	PRESSAO_ART NUMERIC (6),
	BAT_REPOUSO NUMERIC (6),
	NIVEL_COND VARCHAR (20),
	ID_ALUNO INT,
	ID_PERS_RESP INT,

	CONSTRAINT PK_IDAVALIACAO PRIMARY KEY (IDAVALIACAO),
	CONSTRAINT FK_AVA_ALUNO FOREIGN KEY (ID_ALUNO) REFERENCES ALUNO (IDALUNO),
    CONSTRAINT FK_AVA_PERSON FOREIGN KEY (ID_PERS_RESP) REFERENCES PERSONAL (IDPERSONAL)		
);

CREATE TABLE AVA_MEDIDAS (
	IDMEDIDAS SERIAL NOT NULL,
	PESCOCO NUMERIC (6),
	PEITO NUMERIC (6),
	BRACO NUMERIC (6),
	ANTEBRACO NUMERIC (6),
	CINTURA NUMERIC (6),
	QUADRIS NUMERIC (6),
	COXA NUMERIC (6),
	PANTURRILHA NUMERIC (6),
	ID_AVALIACAO INT,

	CONSTRAINT PK_IDMEDIDAS  PRIMARY KEY (IDMEDIDAS, ID_AVALIACAO ),
	CONSTRAINT FK_MED_AVALIACAO FOREIGN KEY (ID_AVALIACAO) REFERENCES AVALIACAO (IDAVALIACAO)
	
);

CREATE TABLE TREINO ( 
	IDTREINO SERIAL NOT NULL,
    TIPO VARCHAR (50),
	DATA_INICIO DATE,
   	DATA_FIM DATE,
    
	ID_ALUNO INT,
	ID_PERSONAL INT,

	CONSTRAINT PK_IDTREINO PRIMARY KEY (IDTREINO),
    
	CONSTRAINT FK_TREINO_ALUNO FOREIGN KEY (ID_ALUNO) REFERENCES ALUNO (IDALUNO),
	CONSTRAINT FK_TREINO_PERSONAL FOREIGN KEY (ID_PERSONAL) REFERENCES PERSONAL (IDPERSONAL)      	 
);

CREATE TABLE EXERCICIOS(
    IDEXERC SERIAL NOT NULL,
  	ID_TREINO INT,
    NOMEEXERC VARCHAR (100) NOT NULL,
    POSICAO VARCHAR (100),
    ACAOPRINC VARCHAR (100),
    OBSERVACAO VARCHAR (240),
    PESO NUMERIC,
    REPET INT,
    SERIE INT, 
    
CONSTRAINT PK_EXERCICIOS PRIMARY KEY(IDEXERC,  ID_TREINO),
CONSTRAINT FK_ID_TREINO FOREIGN KEY (ID_TREINO) REFERENCES TREINO (IDTREINO)
);